Traceback (most recent call last):
  File "/home/uo294340/IS-2025/Maria/P3/udp_servidor3_con_ok.py", line 15, in <module>
    servidor.bind(('localhost', puerto)) 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 98] Address already in use
